In [6]:
import pandas as pd
import pandas.io.sql as sqlio
import psycopg2 as ps

In [9]:
df = pd.read_csv('e_commerce_shopper_behaviour_and_lifestyle.csv', sep=',')

In [12]:
pd.set_option('display.max_columns', None)

In [13]:
df.head()

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,household_size,occupation,ethnicity,language_preference,device_type,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,preferred_payment_method,coupon_usage_frequency,loyalty_program_member,referral_count,product_category_preference,shopping_time_of_day,weekend_shopper,impulse_purchases_per_month,browse_to_buy_ratio,return_frequency,budgeting_style,brand_loyalty_score,impulse_buying_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,stress_from_financial_decisions,overall_stress_level,sleep_quality,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate
0,1,56,Female,Germany,Suburban,90860,Self-employed,Associate Degree,Single,0,5,Healthcare,Other,English,Mobile,4,2405,0,3,445,PayPal,3,1,8,Groceries,Morning,1,2,12,1,Strict,8,1,4,1,8,0,2,22,4,0,0,5,2,7,100,38,14,1,5,10,2,62,7,74,19,2025-06-22,6,1,50
1,2,69,Male,Japan,Suburban,35423,Unemployed,Bachelor,Single,1,2,Finance,Other,Mandarin,Mobile,13,3651,28,6,179,Google Pay,0,1,3,Groceries,Afternoon,1,3,93,12,Loose,4,3,7,1,4,1,5,14,4,4,5,9,8,5,28,19,9,2,17,5,7,54,5,23,8,2026-07-25,3,0,37
2,3,46,Female,India,Urban,21467,Self-employed,Associate Degree,Married,1,6,Healthcare,Other,Hindi,Mobile,10,2045,14,1,26,PayPal,0,0,10,Beauty,Afternoon,0,2,68,5,Moderate,2,2,5,1,6,2,0,14,4,0,0,8,10,10,61,38,1,4,18,3,3,33,7,12,13,2026-02-26,6,0,53
3,4,32,Male,Canada,Urban,41770,Self-employed,Bachelor,Widowed,0,4,Engineering,Hispanic,Hindi,Desktop,16,1611,11,2,403,Credit Card,2,1,0,Groceries,Afternoon,1,3,74,2,Moderate,3,2,0,1,12,1,1,15,0,2,0,9,2,1,78,35,9,2,8,5,9,26,4,19,9,2026-10-27,7,0,98
4,5,60,Female,Japan,Urban,183882,Employed,Associate Degree,Widowed,1,9,Other,Asian,English,Desktop,17,3476,57,3,68,Apple Pay,0,1,0,Groceries,Evening,0,6,34,12,Loose,7,8,9,0,6,5,10,20,5,8,10,5,3,2,27,50,16,0,10,8,0,18,7,30,3,2026-06-23,3,0,86

In [14]:
df.to_csv('shopper_behavior.csv', index=False)

In [15]:
len(df)

1000000

In [17]:
total_missing = df.isnull().sum().sum()
print(total_missing)

0

In [18]:
df.isnull().sum()

user_id                            0
age                                0
gender                             0
country                            0
urban_rural                        0
income_level                       0
employment_status                  0
education_level                    0
relationship_status                0
has_children                       0
household_size                     0
occupation                         0
ethnicity                          0
language_preference                0
device_type                        0
weekly_purchases                   0
monthly_spend                      0
cart_abandonment_rate              0
review_writing_frequency           0
average_order_value                0
preferred_payment_method           0
coupon_usage_frequency             0
loyalty_program_member             0
referral_count                     0
product_category_preference        0
shopping_time_of_day               0
weekend_shopper                    0
impulse_purchases_per_month        0
browse_to_buy_ratio                0
return_frequency                   0
budgeting_style                    0
brand_loyalty_score                0
impulse_buying_score               0
environmental_consciousness        0
health_conscious_shopping          0
travel_frequency                   0
hobby_count                        0
social_media_influence_score       0
reading_habits                     0
exercise_frequency                 0
stress_from_financial_decisions    0
overall_stress_level               0
sleep_quality                      0
physical_activity_level            0
mental_health_score                0
daily_session_time_minutes         0
product_views_per_day              0
ad_views_per_day                   0
ad_clicks_per_day                  0
wishlist_items_count               0
cart_items_average                 0
checkout_abandonments_per_month    0
purchase_conversion_rate           0
app_usage_frequency                0
notification_response_rate         0
account_age_months                 0
last_purchase_date                 0
social_sharing_frequency           0
premium_subscription               0
return_rate                        0
dtype: int64

In [ ]:
df.isnull().sum()
total_missing = df.isnull().sum().sum()
print(total_missing)

In [26]:
df_reduzido = df.iloc[:300000,:]
df_reduzido.head()

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,household_size,occupation,ethnicity,language_preference,device_type,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,preferred_payment_method,coupon_usage_frequency,loyalty_program_member,referral_count,product_category_preference,shopping_time_of_day,weekend_shopper,impulse_purchases_per_month,browse_to_buy_ratio,return_frequency,budgeting_style,brand_loyalty_score,impulse_buying_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,stress_from_financial_decisions,overall_stress_level,sleep_quality,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate
0,1,56,Female,Germany,Suburban,90860,Self-employed,Associate Degree,Single,0,5,Healthcare,Other,English,Mobile,4,2405,0,3,445,PayPal,3,1,8,Groceries,Morning,1,2,12,1,Strict,8,1,4,1,8,0,2,22,4,0,0,5,2,7,100,38,14,1,5,10,2,62,7,74,19,2025-06-22,6,1,50
1,2,69,Male,Japan,Suburban,35423,Unemployed,Bachelor,Single,1,2,Finance,Other,Mandarin,Mobile,13,3651,28,6,179,Google Pay,0,1,3,Groceries,Afternoon,1,3,93,12,Loose,4,3,7,1,4,1,5,14,4,4,5,9,8,5,28,19,9,2,17,5,7,54,5,23,8,2026-07-25,3,0,37
2,3,46,Female,India,Urban,21467,Self-employed,Associate Degree,Married,1,6,Healthcare,Other,Hindi,Mobile,10,2045,14,1,26,PayPal,0,0,10,Beauty,Afternoon,0,2,68,5,Moderate,2,2,5,1,6,2,0,14,4,0,0,8,10,10,61,38,1,4,18,3,3,33,7,12,13,2026-02-26,6,0,53
3,4,32,Male,Canada,Urban,41770,Self-employed,Bachelor,Widowed,0,4,Engineering,Hispanic,Hindi,Desktop,16,1611,11,2,403,Credit Card,2,1,0,Groceries,Afternoon,1,3,74,2,Moderate,3,2,0,1,12,1,1,15,0,2,0,9,2,1,78,35,9,2,8,5,9,26,4,19,9,2026-10-27,7,0,98
4,5,60,Female,Japan,Urban,183882,Employed,Associate Degree,Widowed,1,9,Other,Asian,English,Desktop,17,3476,57,3,68,Apple Pay,0,1,0,Groceries,Evening,0,6,34,12,Loose,7,8,9,0,6,5,10,20,5,8,10,5,3,2,27,50,16,0,10,8,0,18,7,30,3,2026-06-23,3,0,86

In [27]:
len(df_reduzido)

300000

In [31]:
df_reduzido.to_csv('shopper_behavior.csv', index=False)

In [33]:
teste = pd.read_csv('shopper_behavior.csv',sep=',')
teste.head()

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,household_size,occupation,ethnicity,language_preference,device_type,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,preferred_payment_method,coupon_usage_frequency,loyalty_program_member,referral_count,product_category_preference,shopping_time_of_day,weekend_shopper,impulse_purchases_per_month,browse_to_buy_ratio,return_frequency,budgeting_style,brand_loyalty_score,impulse_buying_score,environmental_consciousness,health_conscious_shopping,travel_frequency,hobby_count,social_media_influence_score,reading_habits,exercise_frequency,stress_from_financial_decisions,overall_stress_level,sleep_quality,physical_activity_level,mental_health_score,daily_session_time_minutes,product_views_per_day,ad_views_per_day,ad_clicks_per_day,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate
0,1,56,Female,Germany,Suburban,90860,Self-employed,Associate Degree,Single,0,5,Healthcare,Other,English,Mobile,4,2405,0,3,445,PayPal,3,1,8,Groceries,Morning,1,2,12,1,Strict,8,1,4,1,8,0,2,22,4,0,0,5,2,7,100,38,14,1,5,10,2,62,7,74,19,2025-06-22,6,1,50
1,2,69,Male,Japan,Suburban,35423,Unemployed,Bachelor,Single,1,2,Finance,Other,Mandarin,Mobile,13,3651,28,6,179,Google Pay,0,1,3,Groceries,Afternoon,1,3,93,12,Loose,4,3,7,1,4,1,5,14,4,4,5,9,8,5,28,19,9,2,17,5,7,54,5,23,8,2026-07-25,3,0,37
2,3,46,Female,India,Urban,21467,Self-employed,Associate Degree,Married,1,6,Healthcare,Other,Hindi,Mobile,10,2045,14,1,26,PayPal,0,0,10,Beauty,Afternoon,0,2,68,5,Moderate,2,2,5,1,6,2,0,14,4,0,0,8,10,10,61,38,1,4,18,3,3,33,7,12,13,2026-02-26,6,0,53
3,4,32,Male,Canada,Urban,41770,Self-employed,Bachelor,Widowed,0,4,Engineering,Hispanic,Hindi,Desktop,16,1611,11,2,403,Credit Card,2,1,0,Groceries,Afternoon,1,3,74,2,Moderate,3,2,0,1,12,1,1,15,0,2,0,9,2,1,78,35,9,2,8,5,9,26,4,19,9,2026-10-27,7,0,98
4,5,60,Female,Japan,Urban,183882,Employed,Associate Degree,Widowed,1,9,Other,Asian,English,Desktop,17,3476,57,3,68,Apple Pay,0,1,0,Groceries,Evening,0,6,34,12,Loose,7,8,9,0,6,5,10,20,5,8,10,5,3,2,27,50,16,0,10,8,0,18,7,30,3,2026-06-23,3,0,86

In [34]:
len(teste)

300000